// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/app_start.dart';
import 'api/book_file.dart';
import 'api/book_source.dart';
import 'api/http_source.dart';
import 'api/storage.dart';
import 'api/txt_book.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, List<TxtPageBreakCache>>
  dco_decode_Map_String_list_txt_page_break_cache_None(dynamic raw);

  @protected
  Map<String, TxtPageBreakCache>
  dco_decode_Map_String_txt_page_break_cache_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookChapter dco_decode_book_chapter(dynamic raw);

  @protected
  BookDetail dco_decode_book_detail(dynamic raw);

  @protected
  BookMeta dco_decode_book_meta(dynamic raw);

  @protected
  BookshelfEntry dco_decode_bookshelf_entry(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BookshelfEntry dco_decode_box_autoadd_bookshelf_entry(dynamic raw);

  @protected
  TxtLayoutFeedbackInput dco_decode_box_autoadd_txt_layout_feedback_input(
    dynamic raw,
  );

  @protected
  TxtLayoutTelemetry dco_decode_box_autoadd_txt_layout_telemetry(dynamic raw);

  @protected
  TxtPageCacheSelection dco_decode_box_autoadd_txt_page_cache_selection(
    dynamic raw,
  );

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ChapterIndex dco_decode_chapter_index(dynamic raw);

  @protected
  HttpResponse dco_decode_http_response(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<BookChapter> dco_decode_list_book_chapter(dynamic raw);

  @protected
  List<BookshelfEntry> dco_decode_list_bookshelf_entry(dynamic raw);

  @protected
  List<ChapterIndex> dco_decode_list_chapter_index(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<TxtPageBreakCache>)>
  dco_decode_list_record_string_list_txt_page_break_cache(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(String, TxtPageBreakCache)>
  dco_decode_list_record_string_txt_page_break_cache(dynamic raw);

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<TocEntry> dco_decode_list_toc_entry(dynamic raw);

  @protected
  List<TxtPageBreakCache> dco_decode_list_txt_page_break_cache(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  TxtLayoutTelemetry? dco_decode_opt_box_autoadd_txt_layout_telemetry(
    dynamic raw,
  );

  @protected
  TxtPageCacheSelection? dco_decode_opt_box_autoadd_txt_page_cache_selection(
    dynamic raw,
  );

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  (String, List<TxtPageBreakCache>)
  dco_decode_record_string_list_txt_page_break_cache(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, TxtPageBreakCache) dco_decode_record_string_txt_page_break_cache(
    dynamic raw,
  );

  @protected
  SearchHit dco_decode_search_hit(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  TocEntry dco_decode_toc_entry(dynamic raw);

  @protected
  TxtBookMeta dco_decode_txt_book_meta(dynamic raw);

  @protected
  TxtLayoutCache dco_decode_txt_layout_cache(dynamic raw);

  @protected
  TxtLayoutFeedbackInput dco_decode_txt_layout_feedback_input(dynamic raw);

  @protected
  TxtLayoutTelemetry dco_decode_txt_layout_telemetry(dynamic raw);

  @protected
  TxtPageBreakCache dco_decode_txt_page_break_cache(dynamic raw);

  @protected
  TxtPageCacheSelection dco_decode_txt_page_cache_selection(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, List<TxtPageBreakCache>>
  sse_decode_Map_String_list_txt_page_break_cache_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, TxtPageBreakCache>
  sse_decode_Map_String_txt_page_break_cache_None(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookChapter sse_decode_book_chapter(SseDeserializer deserializer);

  @protected
  BookDetail sse_decode_book_detail(SseDeserializer deserializer);

  @protected
  BookMeta sse_decode_book_meta(SseDeserializer deserializer);

  @protected
  BookshelfEntry sse_decode_bookshelf_entry(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BookshelfEntry sse_decode_box_autoadd_bookshelf_entry(
    SseDeserializer deserializer,
  );

  @protected
  TxtLayoutFeedbackInput sse_decode_box_autoadd_txt_layout_feedback_input(
    SseDeserializer deserializer,
  );

  @protected
  TxtLayoutTelemetry sse_decode_box_autoadd_txt_layout_telemetry(
    SseDeserializer deserializer,
  );

  @protected
  TxtPageCacheSelection sse_decode_box_autoadd_txt_page_cache_selection(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ChapterIndex sse_decode_chapter_index(SseDeserializer deserializer);

  @protected
  HttpResponse sse_decode_http_response(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<BookChapter> sse_decode_list_book_chapter(SseDeserializer deserializer);

  @protected
  List<BookshelfEntry> sse_decode_list_bookshelf_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ChapterIndex> sse_decode_list_chapter_index(
    SseDeserializer deserializer,
  );

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<TxtPageBreakCache>)>
  sse_decode_list_record_string_list_txt_page_break_cache(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, TxtPageBreakCache)>
  sse_decode_list_record_string_txt_page_break_cache(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer);

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<TocEntry> sse_decode_list_toc_entry(SseDeserializer deserializer);

  @protected
  List<TxtPageBreakCache> sse_decode_list_txt_page_break_cache(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  TxtLayoutTelemetry? sse_decode_opt_box_autoadd_txt_layout_telemetry(
    SseDeserializer deserializer,
  );

  @protected
  TxtPageCacheSelection? sse_decode_opt_box_autoadd_txt_page_cache_selection(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  (String, List<TxtPageBreakCache>)
  sse_decode_record_string_list_txt_page_break_cache(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, TxtPageBreakCache) sse_decode_record_string_txt_page_break_cache(
    SseDeserializer deserializer,
  );

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  TocEntry sse_decode_toc_entry(SseDeserializer deserializer);

  @protected
  TxtBookMeta sse_decode_txt_book_meta(SseDeserializer deserializer);

  @protected
  TxtLayoutCache sse_decode_txt_layout_cache(SseDeserializer deserializer);

  @protected
  TxtLayoutFeedbackInput sse_decode_txt_layout_feedback_input(
    SseDeserializer deserializer,
  );

  @protected
  TxtLayoutTelemetry sse_decode_txt_layout_telemetry(
    SseDeserializer deserializer,
  );

  @protected
  TxtPageBreakCache sse_decode_txt_page_break_cache(
    SseDeserializer deserializer,
  );

  @protected
  TxtPageCacheSelection sse_decode_txt_page_cache_selection(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_list_txt_page_break_cache_None(
    Map<String, List<TxtPageBreakCache>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_txt_page_break_cache_None(
    Map<String, TxtPageBreakCache> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book_chapter(BookChapter self, SseSerializer serializer);

  @protected
  void sse_encode_book_detail(BookDetail self, SseSerializer serializer);

  @protected
  void sse_encode_book_meta(BookMeta self, SseSerializer serializer);

  @protected
  void sse_encode_bookshelf_entry(
    BookshelfEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bookshelf_entry(
    BookshelfEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_txt_layout_feedback_input(
    TxtLayoutFeedbackInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_txt_layout_telemetry(
    TxtLayoutTelemetry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_txt_page_cache_selection(
    TxtPageCacheSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_index(ChapterIndex self, SseSerializer serializer);

  @protected
  void sse_encode_http_response(HttpResponse self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_chapter(
    List<BookChapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bookshelf_entry(
    List<BookshelfEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chapter_index(
    List<ChapterIndex> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_txt_page_break_cache(
    List<(String, List<TxtPageBreakCache>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_txt_page_break_cache(
    List<(String, TxtPageBreakCache)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_toc_entry(List<TocEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_txt_page_break_cache(
    List<TxtPageBreakCache> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_txt_layout_telemetry(
    TxtLayoutTelemetry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_txt_page_cache_selection(
    TxtPageCacheSelection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_txt_page_break_cache(
    (String, List<TxtPageBreakCache>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_txt_page_break_cache(
    (String, TxtPageBreakCache) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer);

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_toc_entry(TocEntry self, SseSerializer serializer);

  @protected
  void sse_encode_txt_book_meta(TxtBookMeta self, SseSerializer serializer);

  @protected
  void sse_encode_txt_layout_cache(
    TxtLayoutCache self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_txt_layout_feedback_input(
    TxtLayoutFeedbackInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_txt_layout_telemetry(
    TxtLayoutTelemetry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_txt_page_break_cache(
    TxtPageBreakCache self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_txt_page_cache_selection(
    TxtPageCacheSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
