// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/book_file.dart';
import 'api/book_source.dart';
import 'api/http_source.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'api/txt_book.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -977944047;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_velora',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleEngineVersion();

  int crateApiTxtBookEstimateWordCount({required String text});

  Future<HttpResponse> crateApiHttpSourceFetchUrl({
    required String url,
    required List<(String, String)> headers,
  });

  Future<HttpResponse> crateApiHttpSourceHttpGet({
    required String url,
    required List<(String, String)> headers,
  });

  Future<void> crateApiSimpleInitApp();

  void crateApiStorageInitStorage({required String rootDir});

  List<BookshelfEntry> crateApiStorageListBookshelf();

  BookMeta crateApiBookFileOpenBookBytes({
    required String locator,
    required String title,
    required List<int> bytes,
  });

  BookMeta crateApiBookFileOpenBookFile({required String path});

  TxtBookMeta crateApiTxtBookOpenTxtBook({required String path});

  TxtBookMeta crateApiTxtBookOpenTxtBytes({
    required String locator,
    required String title,
    required List<int> bytes,
  });

  String crateApiBookFileReadBookChapterBytes({
    required String locator,
    required String title,
    required List<int> bytes,
    required BigInt start,
    required BigInt end,
  });

  String crateApiBookFileReadBookChapterFile({
    required String path,
    required BigInt start,
    required BigInt end,
  });

  String crateApiTxtBookReadChapter({
    required String path,
    required BigInt start,
    required BigInt end,
  });

  String crateApiTxtBookReadChapterBytes({
    required List<int> bytes,
    required BigInt start,
    required BigInt end,
  });

  void crateApiStorageRemoveBook({required String id});

  List<SearchHit> crateApiTxtBookSearchInBook({
    required String path,
    required String keyword,
    required int maxHits,
  });

  BookDetail crateApiBookSourceSourceBookDetail({
    required String sourceJson,
    required String bookUrl,
  });

  String crateApiBookSourceSourceChapterContent({
    required String sourceJson,
    required String chapterUrl,
  });

  List<SearchResult> crateApiBookSourceSourceSearch({
    required String sourceJson,
    required String keyword,
  });

  List<TocEntry> crateApiBookSourceSourceToc({
    required String sourceJson,
    required String tocUrl,
  });

  void crateApiStorageUpdateProgress({
    required String id,
    required int chapter,
    required BigInt offset,
    required PlatformInt64 ts,
  });

  void crateApiStorageUpsertBook({required BookshelfEntry entry});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleEngineVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleEngineVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEngineVersionConstMeta =>
      const TaskConstMeta(debugName: "engine_version", argNames: []);

  @override
  int crateApiTxtBookEstimateWordCount({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTxtBookEstimateWordCountConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxtBookEstimateWordCountConstMeta =>
      const TaskConstMeta(debugName: "estimate_word_count", argNames: ["text"]);

  @override
  Future<HttpResponse> crateApiHttpSourceFetchUrl({
    required String url,
    required List<(String, String)> headers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_list_record_string_string(headers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_http_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHttpSourceFetchUrlConstMeta,
        argValues: [url, headers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpSourceFetchUrlConstMeta =>
      const TaskConstMeta(debugName: "fetch_url", argNames: ["url", "headers"]);

  @override
  Future<HttpResponse> crateApiHttpSourceHttpGet({
    required String url,
    required List<(String, String)> headers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_list_record_string_string(headers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_http_response,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiHttpSourceHttpGetConstMeta,
        argValues: [url, headers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpSourceHttpGetConstMeta =>
      const TaskConstMeta(debugName: "http_get", argNames: ["url", "headers"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiStorageInitStorage({required String rootDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStorageInitStorageConstMeta,
        argValues: [rootDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageInitStorageConstMeta =>
      const TaskConstMeta(debugName: "init_storage", argNames: ["rootDir"]);

  @override
  List<BookshelfEntry> crateApiStorageListBookshelf() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bookshelf_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStorageListBookshelfConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageListBookshelfConstMeta =>
      const TaskConstMeta(debugName: "list_bookshelf", argNames: []);

  @override
  BookMeta crateApiBookFileOpenBookBytes({
    required String locator,
    required String title,
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(locator, serializer);
          sse_encode_String(title, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookFileOpenBookBytesConstMeta,
        argValues: [locator, title, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookFileOpenBookBytesConstMeta =>
      const TaskConstMeta(
        debugName: "open_book_bytes",
        argNames: ["locator", "title", "bytes"],
      );

  @override
  BookMeta crateApiBookFileOpenBookFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookFileOpenBookFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookFileOpenBookFileConstMeta =>
      const TaskConstMeta(debugName: "open_book_file", argNames: ["path"]);

  @override
  TxtBookMeta crateApiTxtBookOpenTxtBook({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_txt_book_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTxtBookOpenTxtBookConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxtBookOpenTxtBookConstMeta =>
      const TaskConstMeta(debugName: "open_txt_book", argNames: ["path"]);

  @override
  TxtBookMeta crateApiTxtBookOpenTxtBytes({
    required String locator,
    required String title,
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(locator, serializer);
          sse_encode_String(title, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_txt_book_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTxtBookOpenTxtBytesConstMeta,
        argValues: [locator, title, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxtBookOpenTxtBytesConstMeta =>
      const TaskConstMeta(
        debugName: "open_txt_bytes",
        argNames: ["locator", "title", "bytes"],
      );

  @override
  String crateApiBookFileReadBookChapterBytes({
    required String locator,
    required String title,
    required List<int> bytes,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(locator, serializer);
          sse_encode_String(title, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_u_64(start, serializer);
          sse_encode_u_64(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookFileReadBookChapterBytesConstMeta,
        argValues: [locator, title, bytes, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookFileReadBookChapterBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_book_chapter_bytes",
        argNames: ["locator", "title", "bytes", "start", "end"],
      );

  @override
  String crateApiBookFileReadBookChapterFile({
    required String path,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_64(start, serializer);
          sse_encode_u_64(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookFileReadBookChapterFileConstMeta,
        argValues: [path, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookFileReadBookChapterFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_book_chapter_file",
        argNames: ["path", "start", "end"],
      );

  @override
  String crateApiTxtBookReadChapter({
    required String path,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_64(start, serializer);
          sse_encode_u_64(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTxtBookReadChapterConstMeta,
        argValues: [path, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxtBookReadChapterConstMeta => const TaskConstMeta(
    debugName: "read_chapter",
    argNames: ["path", "start", "end"],
  );

  @override
  String crateApiTxtBookReadChapterBytes({
    required List<int> bytes,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_u_64(start, serializer);
          sse_encode_u_64(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTxtBookReadChapterBytesConstMeta,
        argValues: [bytes, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxtBookReadChapterBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_chapter_bytes",
        argNames: ["bytes", "start", "end"],
      );

  @override
  void crateApiStorageRemoveBook({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStorageRemoveBookConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageRemoveBookConstMeta =>
      const TaskConstMeta(debugName: "remove_book", argNames: ["id"]);

  @override
  List<SearchHit> crateApiTxtBookSearchInBook({
    required String path,
    required String keyword,
    required int maxHits,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(keyword, serializer);
          sse_encode_u_32(maxHits, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_hit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTxtBookSearchInBookConstMeta,
        argValues: [path, keyword, maxHits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTxtBookSearchInBookConstMeta =>
      const TaskConstMeta(
        debugName: "search_in_book",
        argNames: ["path", "keyword", "maxHits"],
      );

  @override
  BookDetail crateApiBookSourceSourceBookDetail({
    required String sourceJson,
    required String bookUrl,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceJson, serializer);
          sse_encode_String(bookUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSourceSourceBookDetailConstMeta,
        argValues: [sourceJson, bookUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSourceSourceBookDetailConstMeta =>
      const TaskConstMeta(
        debugName: "source_book_detail",
        argNames: ["sourceJson", "bookUrl"],
      );

  @override
  String crateApiBookSourceSourceChapterContent({
    required String sourceJson,
    required String chapterUrl,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceJson, serializer);
          sse_encode_String(chapterUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSourceSourceChapterContentConstMeta,
        argValues: [sourceJson, chapterUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSourceSourceChapterContentConstMeta =>
      const TaskConstMeta(
        debugName: "source_chapter_content",
        argNames: ["sourceJson", "chapterUrl"],
      );

  @override
  List<SearchResult> crateApiBookSourceSourceSearch({
    required String sourceJson,
    required String keyword,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceJson, serializer);
          sse_encode_String(keyword, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSourceSourceSearchConstMeta,
        argValues: [sourceJson, keyword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSourceSourceSearchConstMeta =>
      const TaskConstMeta(
        debugName: "source_search",
        argNames: ["sourceJson", "keyword"],
      );

  @override
  List<TocEntry> crateApiBookSourceSourceToc({
    required String sourceJson,
    required String tocUrl,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourceJson, serializer);
          sse_encode_String(tocUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_toc_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSourceSourceTocConstMeta,
        argValues: [sourceJson, tocUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSourceSourceTocConstMeta =>
      const TaskConstMeta(
        debugName: "source_toc",
        argNames: ["sourceJson", "tocUrl"],
      );

  @override
  void crateApiStorageUpdateProgress({
    required String id,
    required int chapter,
    required BigInt offset,
    required PlatformInt64 ts,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_u_32(chapter, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_i_64(ts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStorageUpdateProgressConstMeta,
        argValues: [id, chapter, offset, ts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageUpdateProgressConstMeta =>
      const TaskConstMeta(
        debugName: "update_progress",
        argNames: ["id", "chapter", "offset", "ts"],
      );

  @override
  void crateApiStorageUpsertBook({required BookshelfEntry entry}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bookshelf_entry(entry, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStorageUpsertBookConstMeta,
        argValues: [entry],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageUpsertBookConstMeta =>
      const TaskConstMeta(debugName: "upsert_book", argNames: ["entry"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BookChapter dco_decode_book_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookChapter(
      title: dco_decode_String(arr[0]),
      start: dco_decode_u_64(arr[1]),
      end: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  BookDetail dco_decode_book_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BookDetail(
      name: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      intro: dco_decode_String(arr[2]),
      coverUrl: dco_decode_String(arr[3]),
      tocUrl: dco_decode_String(arr[4]),
    );
  }

  @protected
  BookMeta dco_decode_book_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BookMeta(
      locator: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      author: dco_decode_String(arr[2]),
      format: dco_decode_String(arr[3]),
      encoding: dco_decode_String(arr[4]),
      sizeBytes: dco_decode_u_64(arr[5]),
      coverDataUrl: dco_decode_opt_String(arr[6]),
      chapters: dco_decode_list_book_chapter(arr[7]),
    );
  }

  @protected
  BookshelfEntry dco_decode_bookshelf_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return BookshelfEntry(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      author: dco_decode_String(arr[2]),
      kind: dco_decode_String(arr[3]),
      pathOrUrl: dco_decode_String(arr[4]),
      bookMetaJson: dco_decode_opt_String(arr[5]),
      cover: dco_decode_opt_String(arr[6]),
      lastChapter: dco_decode_u_32(arr[7]),
      lastOffset: dco_decode_u_64(arr[8]),
      updatedAt: dco_decode_i_64(arr[9]),
      sourceName: dco_decode_opt_String(arr[10]),
      sourceJson: dco_decode_opt_String(arr[11]),
      tocUrl: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  BookshelfEntry dco_decode_box_autoadd_bookshelf_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bookshelf_entry(raw);
  }

  @protected
  ChapterIndex dco_decode_chapter_index(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChapterIndex(
      title: dco_decode_String(arr[0]),
      start: dco_decode_u_64(arr[1]),
      end: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  HttpResponse dco_decode_http_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HttpResponse(
      status: dco_decode_u_16(arr[0]),
      body: dco_decode_String(arr[1]),
      encoding: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<BookChapter> dco_decode_list_book_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_chapter).toList();
  }

  @protected
  List<BookshelfEntry> dco_decode_list_bookshelf_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bookshelf_entry).toList();
  }

  @protected
  List<ChapterIndex> dco_decode_list_chapter_index(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_index).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<SearchHit> dco_decode_list_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit).toList();
  }

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_result).toList();
  }

  @protected
  List<TocEntry> dco_decode_list_toc_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_toc_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SearchHit dco_decode_search_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SearchHit(
      offset: dco_decode_u_64(arr[0]),
      preview: dco_decode_String(arr[1]),
    );
  }

  @protected
  SearchResult dco_decode_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchResult(
      name: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      bookUrl: dco_decode_String(arr[2]),
      coverUrl: dco_decode_String(arr[3]),
      sourceName: dco_decode_String(arr[4]),
    );
  }

  @protected
  TocEntry dco_decode_toc_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TocEntry(
      title: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
    );
  }

  @protected
  TxtBookMeta dco_decode_txt_book_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TxtBookMeta(
      path: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      encoding: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
      chapters: dco_decode_list_chapter_index(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BookChapter sse_decode_book_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_start = sse_decode_u_64(deserializer);
    var var_end = sse_decode_u_64(deserializer);
    return BookChapter(title: var_title, start: var_start, end: var_end);
  }

  @protected
  BookDetail sse_decode_book_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_intro = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_tocUrl = sse_decode_String(deserializer);
    return BookDetail(
      name: var_name,
      author: var_author,
      intro: var_intro,
      coverUrl: var_coverUrl,
      tocUrl: var_tocUrl,
    );
  }

  @protected
  BookMeta sse_decode_book_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_locator = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_encoding = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_coverDataUrl = sse_decode_opt_String(deserializer);
    var var_chapters = sse_decode_list_book_chapter(deserializer);
    return BookMeta(
      locator: var_locator,
      title: var_title,
      author: var_author,
      format: var_format,
      encoding: var_encoding,
      sizeBytes: var_sizeBytes,
      coverDataUrl: var_coverDataUrl,
      chapters: var_chapters,
    );
  }

  @protected
  BookshelfEntry sse_decode_bookshelf_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_pathOrUrl = sse_decode_String(deserializer);
    var var_bookMetaJson = sse_decode_opt_String(deserializer);
    var var_cover = sse_decode_opt_String(deserializer);
    var var_lastChapter = sse_decode_u_32(deserializer);
    var var_lastOffset = sse_decode_u_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_sourceName = sse_decode_opt_String(deserializer);
    var var_sourceJson = sse_decode_opt_String(deserializer);
    var var_tocUrl = sse_decode_opt_String(deserializer);
    return BookshelfEntry(
      id: var_id,
      title: var_title,
      author: var_author,
      kind: var_kind,
      pathOrUrl: var_pathOrUrl,
      bookMetaJson: var_bookMetaJson,
      cover: var_cover,
      lastChapter: var_lastChapter,
      lastOffset: var_lastOffset,
      updatedAt: var_updatedAt,
      sourceName: var_sourceName,
      sourceJson: var_sourceJson,
      tocUrl: var_tocUrl,
    );
  }

  @protected
  BookshelfEntry sse_decode_box_autoadd_bookshelf_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bookshelf_entry(deserializer));
  }

  @protected
  ChapterIndex sse_decode_chapter_index(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_start = sse_decode_u_64(deserializer);
    var var_end = sse_decode_u_64(deserializer);
    return ChapterIndex(title: var_title, start: var_start, end: var_end);
  }

  @protected
  HttpResponse sse_decode_http_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_u_16(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_encoding = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    return HttpResponse(
      status: var_status,
      body: var_body,
      encoding: var_encoding,
      url: var_url,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<BookChapter> sse_decode_list_book_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookChapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookshelfEntry> sse_decode_list_bookshelf_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookshelfEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bookshelf_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChapterIndex> sse_decode_list_chapter_index(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterIndex>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_index(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchHit> sse_decode_list_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<TocEntry> sse_decode_list_toc_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TocEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_toc_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SearchHit sse_decode_search_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_u_64(deserializer);
    var var_preview = sse_decode_String(deserializer);
    return SearchHit(offset: var_offset, preview: var_preview);
  }

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_bookUrl = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_sourceName = sse_decode_String(deserializer);
    return SearchResult(
      name: var_name,
      author: var_author,
      bookUrl: var_bookUrl,
      coverUrl: var_coverUrl,
      sourceName: var_sourceName,
    );
  }

  @protected
  TocEntry sse_decode_toc_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    return TocEntry(title: var_title, url: var_url);
  }

  @protected
  TxtBookMeta sse_decode_txt_book_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_encoding = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_chapters = sse_decode_list_chapter_index(deserializer);
    return TxtBookMeta(
      path: var_path,
      title: var_title,
      encoding: var_encoding,
      sizeBytes: var_sizeBytes,
      chapters: var_chapters,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_book_chapter(BookChapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.start, serializer);
    sse_encode_u_64(self.end, serializer);
  }

  @protected
  void sse_encode_book_detail(BookDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.intro, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_String(self.tocUrl, serializer);
  }

  @protected
  void sse_encode_book_meta(BookMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.locator, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_String(self.encoding, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_opt_String(self.coverDataUrl, serializer);
    sse_encode_list_book_chapter(self.chapters, serializer);
  }

  @protected
  void sse_encode_bookshelf_entry(
    BookshelfEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.pathOrUrl, serializer);
    sse_encode_opt_String(self.bookMetaJson, serializer);
    sse_encode_opt_String(self.cover, serializer);
    sse_encode_u_32(self.lastChapter, serializer);
    sse_encode_u_64(self.lastOffset, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_opt_String(self.sourceName, serializer);
    sse_encode_opt_String(self.sourceJson, serializer);
    sse_encode_opt_String(self.tocUrl, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bookshelf_entry(
    BookshelfEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bookshelf_entry(self, serializer);
  }

  @protected
  void sse_encode_chapter_index(ChapterIndex self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.start, serializer);
    sse_encode_u_64(self.end, serializer);
  }

  @protected
  void sse_encode_http_response(HttpResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.status, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.encoding, serializer);
    sse_encode_String(self.url, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_book_chapter(
    List<BookChapter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bookshelf_entry(
    List<BookshelfEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bookshelf_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter_index(
    List<ChapterIndex> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_index(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_hit(
    List<SearchHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_toc_entry(
    List<TocEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_toc_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_search_hit(SearchHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.offset, serializer);
    sse_encode_String(self.preview, serializer);
  }

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.bookUrl, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_String(self.sourceName, serializer);
  }

  @protected
  void sse_encode_toc_entry(TocEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.url, serializer);
  }

  @protected
  void sse_encode_txt_book_meta(TxtBookMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.encoding, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_list_chapter_index(self.chapters, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
