// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `absolute_url`, `select_attr`, `select_resource_url`, `select_text`, `urlencoding_lite`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

List<SearchResult> sourceSearch({
  required String sourceJson,
  required String keyword,
}) => RustLib.instance.api.crateApiBookSourceSourceSearch(
  sourceJson: sourceJson,
  keyword: keyword,
);

BookDetail sourceBookDetail({
  required String sourceJson,
  required String bookUrl,
}) => RustLib.instance.api.crateApiBookSourceSourceBookDetail(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

List<TocEntry> sourceToc({
  required String sourceJson,
  required String tocUrl,
}) => RustLib.instance.api.crateApiBookSourceSourceToc(
  sourceJson: sourceJson,
  tocUrl: tocUrl,
);

String sourceChapterContent({
  required String sourceJson,
  required String chapterUrl,
}) => RustLib.instance.api.crateApiBookSourceSourceChapterContent(
  sourceJson: sourceJson,
  chapterUrl: chapterUrl,
);

class BookDetail {
  final String name;
  final String author;
  final String intro;
  final String coverUrl;
  final String tocUrl;

  const BookDetail({
    required this.name,
    required this.author,
    required this.intro,
    required this.coverUrl,
    required this.tocUrl,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      intro.hashCode ^
      coverUrl.hashCode ^
      tocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookDetail &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          intro == other.intro &&
          coverUrl == other.coverUrl &&
          tocUrl == other.tocUrl;
}

class SearchResult {
  final String name;
  final String author;
  final String bookUrl;
  final String coverUrl;
  final String sourceName;

  const SearchResult({
    required this.name,
    required this.author,
    required this.bookUrl,
    required this.coverUrl,
    required this.sourceName,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      bookUrl.hashCode ^
      coverUrl.hashCode ^
      sourceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          bookUrl == other.bookUrl &&
          coverUrl == other.coverUrl &&
          sourceName == other.sourceName;
}

class TocEntry {
  final String title;
  final String url;

  const TocEntry({required this.title, required this.url});

  @override
  int get hashCode => title.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TocEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url;
}
