// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `be_u16`, `be_u32`, `cached_txt`, `detect_encoding`, `extension`, `extract_epub_cover`, `fallback_title`, `html_title`, `html_to_text`, `join_epub_path`, `meta_from_parsed`, `mime_from_path`, `mobi_encoding`, `normalize_inline`, `normalize_text`, `palmdoc_decompress`, `parse_book`, `parse_chapters`, `parse_epub`, `parse_mobi`, `parse_txt`, `read_text_range`, `read_zip_bytes`, `read_zip_string`, `split_fallback`, `store_txt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EpubManifestItem`, `ParsedBook`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`

BookMeta openBookFile({required String path}) =>
    RustLib.instance.api.crateApiBookFileOpenBookFile(path: path);

BookMeta openBookBytes({
  required String locator,
  required String title,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiBookFileOpenBookBytes(
  locator: locator,
  title: title,
  bytes: bytes,
);

String readBookChapterFile({
  required String path,
  required BigInt start,
  required BigInt end,
}) => RustLib.instance.api.crateApiBookFileReadBookChapterFile(
  path: path,
  start: start,
  end: end,
);

String readBookChapterBytes({
  required String locator,
  required String title,
  required List<int> bytes,
  required BigInt start,
  required BigInt end,
}) => RustLib.instance.api.crateApiBookFileReadBookChapterBytes(
  locator: locator,
  title: title,
  bytes: bytes,
  start: start,
  end: end,
);

class BookChapter {
  final String title;
  final BigInt start;
  final BigInt end;

  const BookChapter({
    required this.title,
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => title.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookChapter &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          start == other.start &&
          end == other.end;
}

class BookMeta {
  final String locator;
  final String title;
  final String author;
  final String format;
  final String encoding;
  final BigInt sizeBytes;
  final String? coverDataUrl;
  final List<BookChapter> chapters;

  const BookMeta({
    required this.locator,
    required this.title,
    required this.author,
    required this.format,
    required this.encoding,
    required this.sizeBytes,
    this.coverDataUrl,
    required this.chapters,
  });

  @override
  int get hashCode =>
      locator.hashCode ^
      title.hashCode ^
      author.hashCode ^
      format.hashCode ^
      encoding.hashCode ^
      sizeBytes.hashCode ^
      coverDataUrl.hashCode ^
      chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMeta &&
          runtimeType == other.runtimeType &&
          locator == other.locator &&
          title == other.title &&
          author == other.author &&
          format == other.format &&
          encoding == other.encoding &&
          sizeBytes == other.sizeBytes &&
          coverDataUrl == other.coverDataUrl &&
          chapters == other.chapters;
}
