// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_once`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FetchOnceError`, `FetchOnceResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

Future<HttpResponse> fetchUrl({
  required String url,
  required List<(String, String)> headers,
}) =>
    RustLib.instance.api.crateApiHttpSourceFetchUrl(url: url, headers: headers);

Future<HttpResponse> httpGet({
  required String url,
  required List<(String, String)> headers,
}) =>
    RustLib.instance.api.crateApiHttpSourceHttpGet(url: url, headers: headers);

class HttpResponse {
  final int status;
  final String body;
  final String encoding;
  final String url;

  const HttpResponse({
    required this.status,
    required this.body,
    required this.encoding,
    required this.url,
  });

  @override
  int get hashCode =>
      status.hashCode ^ body.hashCode ^ encoding.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body &&
          encoding == other.encoding &&
          url == other.url;
}
