// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancellation_failure`, `circuit_gate`, `duration_ms`, `failure`, `fetch_for_source_async`, `fetch_for_source`, `finish_request`, `new`, `open_circuit`, `percentile`, `push_observation`, `record_observation`, `record_source_failure`, `record_source_success`, `record_transport_failure`, `register_request`, `request_host`, `request_timeout`, `retry_after_duration`, `retry_delay`, `snapshot_for`, `source_id`, `source_limiter`, `timestamp_ms`, `trace_observation`, `wait_for_retry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FetchTrace`, `HealthEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

bool cancelSourceRequest({required String requestId}) => RustLib.instance.api
    .crateApiSourceRuntimeCancelSourceRequest(requestId: requestId);

List<SourceHealthSnapshot> sourceHealthSnapshots() =>
    RustLib.instance.api.crateApiSourceRuntimeSourceHealthSnapshots();

List<SourceObservation> sourceRecentObservations({
  String? sourceId,
  required int limit,
}) => RustLib.instance.api.crateApiSourceRuntimeSourceRecentObservations(
  sourceId: sourceId,
  limit: limit,
);

enum CircuitState { healthy, degraded, openCircuit, halfOpen }

enum FailureKind {
  networkTransient,
  rateLimited,
  authDenied,
  resourceGone,
  parserBroken,
  invalidContent,
  invalidRule,
  httpRejected,
  circuitOpen,
  cancelled,
}

class SourceFailureInfo {
  final FailureKind kind;
  final String message;
  final BigInt? retryAfterMs;

  const SourceFailureInfo({
    required this.kind,
    required this.message,
    this.retryAfterMs,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ retryAfterMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceFailureInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          retryAfterMs == other.retryAfterMs;
}

class SourceHealthSnapshot {
  final String sourceId;
  final CircuitState circuitState;
  final BigInt cooldownRemainingMs;
  final double healthScore;
  final double recentSuccessRate;
  final double parserValidRate;
  final BigInt p50LatencyMs;
  final BigInt p95LatencyMs;
  final PlatformInt64? lastSuccessAtMs;
  final FailureKind? recentFailureKind;
  final int observationCount;

  const SourceHealthSnapshot({
    required this.sourceId,
    required this.circuitState,
    required this.cooldownRemainingMs,
    required this.healthScore,
    required this.recentSuccessRate,
    required this.parserValidRate,
    required this.p50LatencyMs,
    required this.p95LatencyMs,
    this.lastSuccessAtMs,
    this.recentFailureKind,
    required this.observationCount,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      circuitState.hashCode ^
      cooldownRemainingMs.hashCode ^
      healthScore.hashCode ^
      recentSuccessRate.hashCode ^
      parserValidRate.hashCode ^
      p50LatencyMs.hashCode ^
      p95LatencyMs.hashCode ^
      lastSuccessAtMs.hashCode ^
      recentFailureKind.hashCode ^
      observationCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceHealthSnapshot &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          circuitState == other.circuitState &&
          cooldownRemainingMs == other.cooldownRemainingMs &&
          healthScore == other.healthScore &&
          recentSuccessRate == other.recentSuccessRate &&
          parserValidRate == other.parserValidRate &&
          p50LatencyMs == other.p50LatencyMs &&
          p95LatencyMs == other.p95LatencyMs &&
          lastSuccessAtMs == other.lastSuccessAtMs &&
          recentFailureKind == other.recentFailureKind &&
          observationCount == other.observationCount;
}

class SourceObservation {
  final String sourceId;
  final SourceOperation operation;
  final String requestHost;
  final int? statusCode;
  final BigInt latencyMs;
  final int retryCount;
  final FailureKind? failureKind;
  final int parsedItems;
  final int textLength;
  final int ruleVersion;
  final bool cacheHit;
  final PlatformInt64 timestampMs;

  const SourceObservation({
    required this.sourceId,
    required this.operation,
    required this.requestHost,
    this.statusCode,
    required this.latencyMs,
    required this.retryCount,
    this.failureKind,
    required this.parsedItems,
    required this.textLength,
    required this.ruleVersion,
    required this.cacheHit,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      operation.hashCode ^
      requestHost.hashCode ^
      statusCode.hashCode ^
      latencyMs.hashCode ^
      retryCount.hashCode ^
      failureKind.hashCode ^
      parsedItems.hashCode ^
      textLength.hashCode ^
      ruleVersion.hashCode ^
      cacheHit.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceObservation &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          operation == other.operation &&
          requestHost == other.requestHost &&
          statusCode == other.statusCode &&
          latencyMs == other.latencyMs &&
          retryCount == other.retryCount &&
          failureKind == other.failureKind &&
          parsedItems == other.parsedItems &&
          textLength == other.textLength &&
          ruleVersion == other.ruleVersion &&
          cacheHit == other.cacheHit &&
          timestampMs == other.timestampMs;
}

enum SourceOperation { search, bookDetail, toc, content }
