// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db_path`, `load_db`, `save_db`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookshelfDb`, `StorageState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

void initStorage({required String rootDir}) =>
    RustLib.instance.api.crateApiStorageInitStorage(rootDir: rootDir);

List<BookshelfEntry> listBookshelf() =>
    RustLib.instance.api.crateApiStorageListBookshelf();

void upsertBook({required BookshelfEntry entry}) =>
    RustLib.instance.api.crateApiStorageUpsertBook(entry: entry);

void removeBook({required String id}) =>
    RustLib.instance.api.crateApiStorageRemoveBook(id: id);

void updateProgress({
  required String id,
  required int chapter,
  required BigInt offset,
  required PlatformInt64 ts,
}) => RustLib.instance.api.crateApiStorageUpdateProgress(
  id: id,
  chapter: chapter,
  offset: offset,
  ts: ts,
);

class BookshelfEntry {
  final String id;
  final String title;
  final String author;
  final String kind;
  final String pathOrUrl;
  final String? bookMetaJson;
  final String? cover;
  final int lastChapter;
  final BigInt lastOffset;
  final PlatformInt64 updatedAt;
  final String? sourceName;
  final String? sourceJson;
  final String? tocUrl;

  const BookshelfEntry({
    required this.id,
    required this.title,
    required this.author,
    required this.kind,
    required this.pathOrUrl,
    this.bookMetaJson,
    this.cover,
    required this.lastChapter,
    required this.lastOffset,
    required this.updatedAt,
    this.sourceName,
    this.sourceJson,
    this.tocUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      kind.hashCode ^
      pathOrUrl.hashCode ^
      bookMetaJson.hashCode ^
      cover.hashCode ^
      lastChapter.hashCode ^
      lastOffset.hashCode ^
      updatedAt.hashCode ^
      sourceName.hashCode ^
      sourceJson.hashCode ^
      tocUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookshelfEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          kind == other.kind &&
          pathOrUrl == other.pathOrUrl &&
          bookMetaJson == other.bookMetaJson &&
          cover == other.cover &&
          lastChapter == other.lastChapter &&
          lastOffset == other.lastOffset &&
          updatedAt == other.updatedAt &&
          sourceName == other.sourceName &&
          sourceJson == other.sourceJson &&
          tocUrl == other.tocUrl;
}
