// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_all`, `detect_encoding`, `meta_from_bytes`, `parse_chapters`, `read_text_range`, `rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

TxtBookMeta openTxtBook({required String path}) =>
    RustLib.instance.api.crateApiTxtBookOpenTxtBook(path: path);

TxtBookMeta openTxtBytes({
  required String locator,
  required String title,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTxtBookOpenTxtBytes(
  locator: locator,
  title: title,
  bytes: bytes,
);

String readChapter({
  required String path,
  required BigInt start,
  required BigInt end,
}) => RustLib.instance.api.crateApiTxtBookReadChapter(
  path: path,
  start: start,
  end: end,
);

String readChapterBytes({
  required List<int> bytes,
  required BigInt start,
  required BigInt end,
}) => RustLib.instance.api.crateApiTxtBookReadChapterBytes(
  bytes: bytes,
  start: start,
  end: end,
);

int estimateWordCount({required String text}) =>
    RustLib.instance.api.crateApiTxtBookEstimateWordCount(text: text);

List<SearchHit> searchInBook({
  required String path,
  required String keyword,
  required int maxHits,
}) => RustLib.instance.api.crateApiTxtBookSearchInBook(
  path: path,
  keyword: keyword,
  maxHits: maxHits,
);

class ChapterIndex {
  final String title;
  final BigInt start;
  final BigInt end;

  const ChapterIndex({
    required this.title,
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => title.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterIndex &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          start == other.start &&
          end == other.end;
}

class SearchHit {
  final BigInt offset;
  final String preview;

  const SearchHit({required this.offset, required this.preview});

  @override
  int get hashCode => offset.hashCode ^ preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          preview == other.preview;
}

class TxtBookMeta {
  final String path;
  final String title;
  final String encoding;
  final BigInt sizeBytes;
  final List<ChapterIndex> chapters;

  const TxtBookMeta({
    required this.path,
    required this.title,
    required this.encoding,
    required this.sizeBytes,
    required this.chapters,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      encoding.hashCode ^
      sizeBytes.hashCode ^
      chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxtBookMeta &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          encoding == other.encoding &&
          sizeBytes == other.sizeBytes &&
          chapters == other.chapters;
}
